import type { AnalysisResult, Consequence } from '../shared/types.js';
import { formatCausalChainInline } from '../explain/chain.js';

export function exportMarkdown(result: AnalysisResult): string {
  const lines: string[] = [];

  lines.push(`# Diffsequence Analysis Report`);
  lines.push('');
  lines.push(`**Repository:** ${result.repository}`);
  lines.push(`**Branch:** ${result.branch}`);
  lines.push(`**Files Changed:** ${result.filesChanged}`);
  lines.push(`**Date:** ${new Date(result.timestamp).toLocaleString()}`);
  lines.push('');

  // summary
  lines.push(`## Summary`);
  lines.push('');
  lines.push(result.summary.verdict);
  lines.push('');
  lines.push(`| Level | Count |`);
  lines.push(`|-------|-------|`);
  lines.push(`| 🔴 Critical | ${result.summary.criticalCount} |`);
  lines.push(`| 🟠 High | ${result.summary.highCount} |`);
  lines.push(`| 🟡 Medium | ${result.summary.mediumCount} |`);
  lines.push(`| 🟢 Low | ${result.summary.lowCount} |`);
  lines.push('');

  if (result.summary.topRisks.length > 0) {
    lines.push(`### Top Risks`);
    lines.push('');
    for (const risk of result.summary.topRisks) {
      lines.push(`1. ${risk}`);
    }
    lines.push('');
  }

  // consequences
  lines.push(`## Consequences`);
  lines.push('');

  for (const c of result.consequences) {
    lines.push(formatConsequence(c));
    lines.push('');
  }

  // metadata
  lines.push(`## Analysis Metadata`);
  lines.push('');
  lines.push(`| Metric | Value |`);
  lines.push(`|--------|-------|`);
  lines.push(`| Analysis Time | ${result.metadata.analysisTimeMs}ms |`);
  lines.push(`| Files Scanned | ${result.metadata.filesScanned} |`);
  lines.push(`| Symbols Indexed | ${result.metadata.symbolsIndexed} |`);
  lines.push(`| Graph Edges | ${result.metadata.graphEdges} |`);
  lines.push('');
  lines.push('*Generated by [Diffsequence](https://github.com/diffsequence/diffsequence)*');

  return lines.join('\n');
}

function formatConsequence(c: Consequence): string {
  const riskIcon = getRiskIcon(c.riskLevel);
  const lines: string[] = [];

  lines.push(`### ${riskIcon} ${c.title}`);
  lines.push('');
  lines.push(`**Risk:** ${c.riskLevel.toUpperCase()} (${c.riskScore}/100) · **Confidence:** ${Math.round(c.confidence.score * 100)}%`);
  lines.push(`**Type:** ${formatType(c.type)}`);
  lines.push(`**Affected:** \`${c.affectedFile}\``);
  lines.push(`**Source:** \`${c.sourceFile}\``);
  lines.push('');
  lines.push(c.description);
  lines.push('');

  if (c.causalChain.length > 1) {
    lines.push(`**Impact Chain:** ${formatCausalChainInline(c.causalChain)}`);
    lines.push('');
  }

  if (c.reasoning) {
    lines.push(`**Reasoning:** ${c.reasoning}`);
    lines.push('');
  }

  if (c.verificationSteps.length > 0) {
    lines.push(`**Verification:**`);
    for (const step of c.verificationSteps) {
      lines.push(`- [ ] ${step}`);
    }
  }

  return lines.join('\n');
}

function getRiskIcon(level: string): string {
  switch (level) {
    case 'critical': return '🔴';
    case 'high': return '🟠';
    case 'medium': return '🟡';
    case 'low': return '🟢';
    default: return '⚪';
  }
}

function formatType(type: string): string {
  return type.replace(/_/g, ' ').replace(/\b\w/g, (c) => c.toUpperCase());
}
